InfoColeAplicacion/Models/Alerta.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace InfoColeAplicacion.Models
{
    public class Alerta
    {
        public int ID { get; set; }
        [Required(ErrorMessage = "El campo Contenido es requerido")]
        public string Contenido { get; set; }
        public DateTime Fecha { get; set; }

        [Required(ErrorMessage = "El campo Tipo es requerido")]
        public int TipoID { get; set; }
        public TipoAlerta Tipo { get; set; }
    }
}

InfoColeAplicacion/Models/EstadoLinea.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace InfoColeAplicacion.Models
{
    public class EstadoLinea
    {
        public int ID { get; set; }
        [Required(ErrorMessage = "El campo Contenido es requerido")]
        public string Contenido { get; set; }
        public DateTime Fecha { get; set; }

        [Required(ErrorMessage = "El campo Tipo es requerido")]
        public int TipoID { get; set; }
        public TipoAlerta Tipo { get; set; }

        public int LineaID { get; set; }
        public virtual Linea Linea { get; set; }
    }
}

InfoColeAplicacion/Controllers/AlertasController.cs
using InfoColeAplicacion.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InfoColeAplicacion.Controllers
{
    public class AlertasController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Alertas
        public ActionResult Index()
        {
            CargarTiposDropDownList();
            CargarLineasDropDown();
            return View();
        }


        public PartialViewResult CrearAlertaTrafico()
        {
            CargarTiposDropDownList();
            CargarLineasDropDown();
            return PartialView("CrearAlertaTrafico");
        }

        [HttpPost]
        public ActionResult CrearAlertaTrafico(Transito publicacion)
        {
            if (!ModelState.IsValid)
            {
                MsgBox("Incorrecto, por favor revise los campos e intente nuevamente. ");
                CargarTiposDropDownList(publicacion);
                CargarLineasDropDown();
                return View("Index");
            }
            else
            {

                publicacion.Fecha = DateTime.Now;
                db.Transitos.Add(publicacion);
                db.SaveChanges();
                CargarTiposDropDownList();
                CargarLineasDropDown();
                MsgBox("Exito al guardar el alerta de Transito.");
                ModelState.Clear();
                return View("Index");
            }
        }

        //GET
        public PartialViewResult AlertaLineas()
        {
            CargarTiposDropDownList();
            CargarLineasDropDown();
            return PartialView("AlertaLineas");
        }

        //POST
        [HttpPost]
        public ActionResult AlertaLineas(Alerta publicacion)
        {
            if (!ModelState.IsValid)
            {
                MsgBox("Incorrecto, por favor revise los campos e intente nuevamente. ");
                CargarLineasDropDown(publicacion);
                CargarTiposDropDownList();
                return View("Index");
            }
            else
            {
                publicacion.Fecha = DateTime.Now;
                db.Alertas.Add(publicacion);
                db.SaveChanges();
                CargarTiposDropDownList();
                CargarLineasDropDown();
                MsgBox("Exito al agregar alerta.");
                ModelState.Clear();
                return View("Index");
            }
        }

        public PartialViewResult EstadoLineas()
        {
            CargarTiposDropDownList();
            CargarLineasDropDown();
            return PartialView("EstadoLineas");
        }

        //POST
        [HttpPost]
        public ActionResult EstadoLineas(EstadoLinea publicacion)
        {
            if (!ModelState.IsValid)
            {
                MsgBox("Incorrecto, por favor revise los campos e intente nuevamente. ");
                CargarLineasDropDown(publicacion);
                CargarTiposDropDownList();
                return View("Index");
            }
            else
            {

                EstadoLinea lineas = db.EstadoLineas.Where(c => c.LineaID == publicacion.LineaID).FirstOrDefault();
                publicacion.Fecha = DateTime.Now;
                if (lineas != null)
                {
                    lineas.Fecha = publicacion.Fecha;
                    lineas.Contenido = publicacion.Contenido;
                    lineas.TipoID = publicacion.TipoID;
                    db.Entry(lineas).State = EntityState.Modified;
                    db.SaveChanges();
                }
                else {
                    db.EstadoLineas.Add(publicacion);
                    db.SaveChanges();
                }
                CargarTiposDropDownList();
                CargarLineasDropDown();
                MsgBox("Exito al agregar alerta.");
                ModelState.Clear();
                return View("Index");
            }
        }

        private void LimpiarCampos()
        {
            ModelState.Clear();
        }

        private void CargarTiposDropDownList(object tipoSelecionado = null)
        {
            var tiposQuery = from d in db.TipoAlertas
                             select d;
            ViewBag.TipoID = new SelectList(tiposQuery, "TipoID", "Nombre", tipoSelecionado);
        }

        private void CargarLineasDropDown(object tipoSelecionado = null)
        {
            var lineas = from d in db.Lineas
                         select d;
            ViewBag.LineaID = new SelectList(lineas, "ID", "Nombre", tipoSelecionado);
        }

        private void MsgBox(string mensaje)
        {
            string msg = "<script language=\"javascript\">";
            msg += "alert('" + mensaje + "');";
            msg += "</script>";
            Response.Write(msg);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


    }
}

InfoColeAplicacion/Views/Alertas/AlertaLineas.cshtml
@{
    Layout = null;
}

@model InfoColeAplicacion.Models.Alerta

@using (Html.BeginForm("AlertaLineas", "Alertas", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div id="AlertaLineas">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div>
            Tipo:
            @Html.DropDownList("TipoID", (SelectList)ViewBag.TipoID, "Seleccione el tipo", new { @class = "form-control", @style = "width: 200px" })
            @Html.ValidationMessageFor(model => model.TipoID)
        </div>
        <br />
        <div>
            @Html.TextAreaFor(model => model.Contenido, 2, 50, new { htmlAttributes = new { @class = "form-control textarea1" } })
            @Html.ValidationMessageFor(model => model.Contenido)
        </div>
        <input type="submit" name="submitAlerta" value="Publicar Alerta" />
        <input type="reset" value="Cancelar">
    </div>
}

InfoColeAplicacion/Views/Alertas/CrearAlertaTrafico.cshtml
@{
    Layout = null;
}

@model InfoColeAplicacion.Models.Transito

@using (Html.BeginForm("CrearAlertaTrafico", "Alertas", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div id="AlertaTransito"  class="justify-content-center text-center d-block" style="margin:auto">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div>
            Tipo:
            @Html.DropDownList("TipoID", (SelectList)ViewBag.TipoID, "Seleccione el tipo", new { @class = "form-control", @style = "width: 400px; margin:auto" })
            @Html.ValidationMessageFor(model => model.TipoID)
        </div>
        <br />
        <div>
            @Html.TextAreaFor(model => model.Contenido, 2, 30, new { htmlAttributes = new { @class = "form-control textarea1" } })
            @Html.ValidationMessageFor(model => model.Contenido)
        </div>
        <input type="submit" name="submitButton" value="Publicar Alerta" />
        <input type="reset" value="Cancelar">
    </div>
}

InfoColeAplicacion/Views/Alertas/EstadoLineas.cshtml
@model InfoColeAplicacion.Models.EstadoLinea

@{
    Layout = null;
}


@using (Html.BeginForm("EstadoLineas", "Alertas", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div id="EstadoLineas">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div>
            Tipo:
            @Html.DropDownList("TipoID", (SelectList)ViewBag.TipoID, "Seleccione el tipo", new { @class = "form-control", @style = "width: 200px" })
            @Html.ValidationMessageFor(model => model.TipoID)
        </div>
        <br />
        <div>
            Lineas:
            @Html.DropDownList("LineaID", (SelectList)ViewBag.LineaID, "Seleccione la linea", new { @class = "form-control", @style = "width : 200px" })
            @Html.ValidationMessageFor(model => model.LineaID)
        </div>
        <br />
        <div>
            @Html.TextAreaFor(model => model.Contenido, 2, 50, new { htmlAttributes = new { @class = "form-control textarea1" } })
            @Html.ValidationMessageFor(model => model.Contenido)
        </div>
        <input type="submit" name="submitAlerta" value="Publicar estado de Linea" />
        <input type="reset" value="Cancelar">
    </div>

}

InfoColeAplicacion/Views/Alertas/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div class=" container-fluid">
    <div>
        <h3>Estado del tránsito</h3>
        <div class="alert alert-dark text-center justify-content-center" role="alert">
            @{Html.RenderPartial("CrearAlertaTrafico");}
        </div>


    </div>
    <div>
        <div class="row" style="height:100%">
            <div class="col-md-8 float-left">
                <h3>Alertas</h3>
                <br />
                <div>
                    @{Html.RenderPartial("AlertaLineas");}
                </div>
            </div>

            <div class="col-md-4 float-right">
                <div class="text-center">
                    <h3>Estado de las líneas</h3>
                </div>
                <br />
                <div>
                    @{Html.RenderPartial("EstadoLineas");}
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}