InfoColeAplicacion/Models/Ruta.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace InfoColeAplicacion.Models
{
    public class Ruta
    {
        [Key]
        public int RutaId { get; set; }

        public virtual List<PuntoRuta> Puntos { get; set; }

        
        public int ID { get; set; }
        public Linea Linea { get; set; }
    }
}

InfoColeAplicacion/Controllers/RutasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using InfoColeAplicacion.Models;

namespace InfoColeAplicacion.Controllers
{
    public class RutasController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Rutas
        public ActionResult Index()
        {
            
            ViewBag.ID = new SelectList(db.Lineas, "ID", "Nombre");
            return View();
        }

        public ActionResult IndexUser()
        {
            ViewBag.ID = new SelectList(db.Lineas, "ID", "Nombre");
            return View();
        }


        [HttpGet]
        public JsonResult GetRutas()
        {
            try
            {
                var rutas = db.Rutas.Include(r => r.Puntos).Include(r => r.Linea).ToList();
                var data = rutas.Select(r => new {
                    RutaId = r.RutaId,
                    Puntos = r.Puntos,
                    Linea = r.Linea
                });
                return Json(data, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(ex.Message);
            }
        }

        [HttpGet]
        public JsonResult GetRutasByLinea(int lineaId)
        {
            try
            {
                var rutas = db.Rutas.Where( r => r.ID == lineaId).Include(r => r.Puntos).Include(r => r.Linea).ToList();
                var data = rutas.Select(r => new {
                    RutaId = r.RutaId,
                    Puntos = r.Puntos,
                    Linea = r.Linea
                });
                
                return Json(data, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(ex.Message);
            }
        }


        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ruta ruta = db.Rutas.Find(id);
            if (ruta == null)
            {
                return HttpNotFound();
            }
            return View(ruta);
        }

        
        public ActionResult Create()
        {
            ViewBag.ID = new SelectList(db.Lineas, "ID", "Nombre");
            return View();
        }


        [HttpPost]
        public ActionResult Create(Ruta ruta)
        {
            if (ModelState.IsValid && ruta.Puntos.Count > 0)
            {
                var verificar = db.Rutas.Where(r => r.ID == ruta.ID).FirstOrDefault();
                if(verificar == null)
                {
                    db.Rutas.Add(ruta);
                    db.SaveChanges();
                    return Json("Ruta guardada correctamente", JsonRequestBehavior.AllowGet);
                }
                return Json("Ya se ha registrado una ruta para esta linea", JsonRequestBehavior.AllowGet);

            }

            return Json("Complete correctamente los campos");
        }


        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ruta ruta = db.Rutas.Find(id);
            if (ruta == null)
            {
                return HttpNotFound();
            }
            ViewBag.ID = new SelectList(db.Lineas, "ID", "Nombre", ruta.ID);
            return Json(ruta,JsonRequestBehavior.AllowGet);
        }

        // POST: Rutas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //public ActionResult Edit(Ruta ruta)
        //{
        //    foreach(PuntoRuta punto in ruta.Puntos)
        //    {
        //        //if(punto.Lat == "0")
        //        //{
        //        //    db.Entry(punto).State = EntityState.Deleted;
        //        //    //db.SaveChanges();
        //        //}
        //        if(punto.PuntoMapaId == 0)
        //        {
        //            db.Entry(punto).State = EntityState.Added;
        //            //db.SaveChanges();
        //        }
        //    }


        //    if (ModelState.IsValid)
        //    { 
        //        db.Entry(ruta).State = EntityState.Modified;
               
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    ViewBag.ID = new SelectList(db.Lineas, "ID", "Nombre", ruta.ID);
        //    return View(ruta);
        //}

        // GET: Rutas/Delete/5
        public ActionResult Delete(int? id)
        {
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                Ruta ruta = db.Rutas.Find(id);

                if (ruta == null)
                {
                    return HttpNotFound();
                }
                else
                {
                    db.Rutas.Remove(ruta);
                    db.SaveChanges();
                    return Json("LA RUTA SE ELIMINO CON EXITO");
                }
            }
            catch (Exception ex)
            {
                return Json("SE PRODUJO UN ERROR, INTENTE NUEVAMENTE");
            }
        }



        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

InfoColeAplicacion/Views/Rutas/Create.cshtml
@model InfoColeAplicacion.Models.Ruta

<style>
    #map {
        height: 400px; 
        width: 100%; 
    }
</style>

<h2>Crear</h2>

<div class="row">
    
    <div id="map" class="col-md-8 col-sm-12"></div>
    
    <div class="form-horizontal col-md-4">
        <h4>Ruta</h4>
        <hr />

        <div class="form-group">
            <label class="control-label col-md-2" for="ID">Linea</label>
            <div class="col-md-10">
                @Html.DropDownList("ID", null, htmlAttributes: new { @class = "form-control elements" })
                @Html.ValidationMessageFor(model => model.ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" id="guardar" value="Guardar" class="btn btn-success elements" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button id="remover" disabled class="btn btn-danger elements">Remover ultimo</button>
            </div>
        </div>
        <div>
            @Html.ActionLink("Volver", "Index", null, htmlAttributes: new { @class = "btn btn-primary elements" })
        </div>
    </div>
       
</div>







@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jquery")
    <script>

        var map;
        var markers = [];
        startPosition = {};
        startPosition.Lat = 0.0;
        startPosition.Long = 0.0;

        //Solicita permiso para acceder a la posicion del dispositivo
        //De ser denega la solicitud, el centro del mapa se situa en el centro de la plaza 25 de mayo
        function initScript() {
            navigator.geolocation.getCurrentPosition((position) => {

                this.startPosition.Lat = position.coords.latitude;
                this.startPosition.Long = position.coords.longitude;

                var position = { lat: this.startPosition.Lat, lng: this.startPosition.Long };
                initMap(position);
            }, () => {
                this.startPosition.Lat = -27.451102018823633;
                this.startPosition.Long = -58.98655582728293;
                var position = { lat: this.startPosition.Lat, lng: this.startPosition.Long };
                initMap(position);
                });
        }


        //Inicia el mapa
        function initMap(position) {
            
            map = new google.maps.Map(
                document.getElementById('map'), { zoom: 16, center: position });

            poly = new google.maps.Polyline({
                strokeColor: '#000000',
                strokeOpacity: 0.4,
                strokeWeight: 3
            });
            poly.setMap(map);
            // Add a listener for the click event
            map.addListener('click', addLatLng);
        }

        //Agrega un punto a la ruta
        function addLatLng(event) {
            if (poly.getPath().length == 0) {
                $('#remover').removeAttr('disabled');
            }
            let path = poly.getPath();

            path.push(event.latLng);
            
            var marker = new google.maps.Marker({
                position: event.latLng,
                map: map
            });
            markers.push(marker);
        }

        //Llamada ajax al metodo de crear
        $("#guardar").click(function (e){
            e.preventDefault();
            let puntos = [];
            for (let i = 0; i < markers.length; i++) {
                var punto = {
                    Lat : "",
                    Long : ""
                };
                punto.Lat = markers[i].position.lat();
                punto.Long = markers[i].position.lng();
                puntos.push(punto);
            }
            let data = {};
            data.ID = $('#ID').val() * 1;
            data.Puntos = puntos;
            let url = "@Url.Action("Create", "Rutas")";
            $.post(url, data).done(
                (mensaje) => {

                    //Quita todos los puntos del mapa
                    for (let i = markers.length - 1; i >= 0; i--) {
                        markers[i].setMap(null);
                        markers[i] = null;        
                    }
                    markers = [];

                    //Quita todas las lineas del mapa
                    for (let i = poly.getPath().length - 1; i >= 0; i--) {
                        poly.getPath()[i] = null;
                        poly.getPath().pop();
                    }
                    alert(mensaje);
                    $('#remover').attr('disabled','disabled');
                }
            ).fail(
                () => { alert("Se ha producido un error,intente nuevamente"); }               
            );
        })

        //Remueve el ultimo punto agregado
        $('#remover').click(() => {
            
            let path = poly.getPath();
            if (path.length > 0) {
                path.pop();
                markers.pop().setMap(null);
                if (path.length == 0) {
                    $('#remover').attr('disabled','disabled');
                }
                console.log(path.length);
            }
            
        }
        )

    </script>


    <script async defer
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDT4I8iAS4V_drotpXRjk1RjRZsAuKhxqU&callback=initScript">
    </script>
}

InfoColeAplicacion/Views/Rutas/Delete.cshtml
@model InfoColeAplicacion.Models.Ruta

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Ruta</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Linea.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Linea.Nombre)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

InfoColeAplicacion/Views/Rutas/Details.cshtml
@model InfoColeAplicacion.Models.Ruta

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Ruta</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Linea.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Linea.Nombre)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.RutaId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

InfoColeAplicacion/Views/Rutas/Edit.cshtml
@model InfoColeAplicacion.Models.Ruta

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Ruta</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.RutaId)

        <div class="form-group">
            @Html.LabelFor(model => model.ID, "ID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

InfoColeAplicacion/Views/Rutas/IndexUser.cshtml
<style>
    #map {
        height: 400px;
        width: 100%;
    }
</style>

<h4 style="font-family: Verdana">Recorridos del transporte público</h4>
<br />
<div class="row">
    <div class="form-group col-md-4 my-auto row">
        <label class="control-label col-md-2 mt-auto mb-auto" style="font-family: Verdana" for="ID">Linea: </label>
        <div class="col-md-10">
            @Html.DropDownList("ID", null, htmlAttributes: new { @class = "form-control elements" })
        </div>
    </div>
    <button id="filtrarPorLinea" class="btn btn-primary ml-3 my-auto elements">Buscar</button>
    <br />
    <br />

</div>

<div class="row">
    <div id="map"></div>
</div>


@section Scripts{
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jquery")

    <script>
        var map;
        var markers = [];
        var rutas = [];
        var selectedRoute = {};
        var startPosition = {};
        var poly = {};
        function initScript() {
            navigator.geolocation.getCurrentPosition((position) => {

                this.startPosition.Lat = position.coords.latitude;
                this.startPosition.Long = position.coords.longitude;

                var position = { lat: this.startPosition.Lat, lng: this.startPosition.Long };
                initMap(position);
            }, () => {
                this.startPosition.Lat = -27.451102018823633;
                this.startPosition.Long = -58.98655582728293;
                var position = { lat: this.startPosition.Lat, lng: this.startPosition.Long };
                initMap(position);
            });
        }

        function initMap(position) {
            map = new google.maps.Map(
                document.getElementById('map'), { zoom: 16, center: position });
            let url = "@Url.Action("Get")";
            poly = new google.maps.Polyline({
                strokeColor: '#000000',
                strokeOpacity: 1.0,
                strokeWeight: 3
            });
            poly.setMap(map);
        }

        $('#filtrarPorLinea').click(function (e) {
            console.log(selectedRoute.Id);
            var url = "@Url.Action("GetRutasByLinea", "Rutas")";
            var id = {};
            id.lineaId = $('#ID').val() * 1;
            $.get(url, id).done(
                function (data) {
                    LimpiarMapa();
                    if (data.length == 0) {
                        alert("No se ha registrado una ruta para la linea seleccionada");
                    }
                    else {
                        //Carga la ruta devuelta por el servidor
                        for (let j = 0; j < data.length; j++) {

                            var path = poly.getPath();
                            for (var i = 0; i < data[j].Puntos.length; i++) {
                                let latitud = parseFloat(data[j].Puntos[i].Lat);
                                let longitud = parseFloat(data[j].Puntos[i].Long);

                                //Si el indice es 0,significa que es el punto inicial,este se mostrar en el mapa
                                if (i == 0) {
                                    var marker = new google.maps.Marker({
                                        position: { lat: latitud, lng: longitud },
                                        map: map,
                                        icon: "/Images/Mapas/LocationPoint.png",
                                        title: 'Inicio del recorrido Linea: ' + data[j].Linea.Nombre,
                                    });
                                    markers.push(marker);
                                    var rutaId = data[j].RutaId;

                                }
                                else {
                                    var marker = new google.maps.Marker({
                                        position: { lat: latitud, lng: longitud },
                                    });
                                }
                                path.push(marker.position);
                            }
                            rutas.push(poly);//verificar si se utiliza este array
                        }
                    }
                }
            ).fail(() => alert("Ajax call failed"))
        })


        function LimpiarMapa() {
            //Quita todos los puntos del mapa
            for (let i = markers.length - 1; i >= 0; i--) {
                markers[i].setMap(null);
                markers[i] = null;
            }
            markers = [];
            //Quita todas las lineas del mapa
            for (let i = poly.getPath().length - 1; i >= 0; i--) {
                poly.getPath()[i] = null;
                poly.getPath().pop();
            }
        }


    </script>




    <script async defer
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDT4I8iAS4V_drotpXRjk1RjRZsAuKhxqU&callback=initScript">
    </script>
}