InfoColeAplicacion/Models/PuntoMapa.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace InfoColeAplicacion.Models
{
    public class PuntoMapa
    {
        [Key]
        public int PuntoMapaId { get; set; }

        [Required(ErrorMessage ="El campo {0} es obligatorio")]
        [MaxLength(100)]
        public string Nombre { get; set; }
        
        [Required(ErrorMessage ="El campo {0} es obligatorio")]
        public string Descripcion { get; set; }

        [Required]
        public string Long { get; set; }

        [Required]
        public string Lat { get; set; }

        public int TipoPuntoMapaId { get; set; }
        public TipoPuntoMapa Tipo { get; set; }
    }
}

InfoColeAplicacion/Controllers/PuntoMapaController.cs
using InfoColeAplicacion.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace InfoColeAplicacion.Controllers
{
    public class PuntoMapaController : Controller
    {

        private ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult Index()
        {
            ViewBag.Tipos = this.ObtenerTipos();
            return View();
        }

        public ActionResult IndexUser()
        {
            ViewBag.Tipos = this.ObtenerTipos();
            return View();
        }

        public List<SelectListItem> ObtenerTipos()
        {
            List<SelectListItem> listado =  new List<SelectListItem>();
            var tipos = db.TiposPuntoMapa.ToList();
            foreach(TipoPuntoMapa tipo in tipos)
            {
                listado.Add(new SelectListItem {Text = tipo.Nombre, Value = tipo.TipoPuntoMapaId.ToString() });
            }
            return listado;
        }

        [HttpGet]
        public JsonResult GetLocations()
        {

            return Json(db.Puntos.Include(p => p.Tipo).ToList(), JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult GetLocationsByType(int tipo)
        {
            return Json(db.Puntos.Include(p => p.Tipo).Where(p => p.TipoPuntoMapaId == tipo).ToList(), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult EditarPunto(PuntoMapa punto)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    db.Entry(punto).State = EntityState.Modified;
                    db.SaveChanges();
                    return Json("EL PUNTO SE EDITO CON EXITO");
                }
                catch(Exception ex)
                {
                    return Json("Se ha producido un error");
                }
            }

            return Json("LA OPERACIÓN FALLO, VUELVa A INTENTARLO");
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                PuntoMapa puntoMapa = db.Puntos.Find(id);

                if (puntoMapa == null)
                {
                    return HttpNotFound();
                }
                else
                {
                    db.Puntos.Remove(puntoMapa);
                    db.SaveChanges();
                    return Json("EL PUNTO SE ELIMINO CON EXITO");
                }
            }
            catch (Exception ex)
            {
                return Json("SE PRODUJO UN ERROR, INTENTE NUEVAMENTE");
            }
        }

        public ActionResult Create()
        {
            ViewBag.Tipos = this.ObtenerTipos();
            return View();
        }


        [HttpPost]
        public ActionResult Create(PuntoMapa puntoMapa)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    db.Puntos.Add(puntoMapa);
                    db.SaveChanges();
                    return Json("El punto se ha guardado correctamente");
                }
                catch(Exception ex)
                {
                    return Json("Se ha producido un error");
                }
            }

            return Json("Ingrese correctamente los datos");
        }
    }
}

InfoColeAplicacion/Views/PuntoMapa/Create.cshtml
@model InfoColeAplicacion.Models.PuntoMapa

<style>
    #map {
        height: 400px;
        width: 100%;
    }
</style>

@using (Html.BeginForm())
{
    // @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control elements" } })
            @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control elements" } })
            @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Tipo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.TipoPuntoMapaId, (List<SelectListItem>)ViewBag.Tipos, new { htmlAttributes = new { @class = "form-control elements" } })
            @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
        </div>
    </div>
    <button id="remover" disabled class="btn btn-primary btn-lg btn-block elements">Remover punto</button>



    <!--The div element for the map -->
    <div id="map"></div>


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" id="submit" value="Crear" class="btn btn-success elements" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Volver al listado", "Index",null, new {@class = "btn btn-primary elements"})
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jquery")
    <script>

        var map;
        var marker;
        var startPosition = {};
        startPosition.Lat = 0.0;
        startPosition.Long = 0.0;
        
        //Inicia el mapa
        function initScript() {
            navigator.geolocation.getCurrentPosition((position) => {

                this.startPosition.Lat = position.coords.latitude;
                this.startPosition.Long = position.coords.longitude;

                var position = { lat: this.startPosition.Lat, lng: this.startPosition.Long };
                initMap(position);
            });         
        }

        //Inicia el mapa y establece su posicion inicial
        function initMap(position) {
            map = new google.maps.Map(
                document.getElementById('map'), { zoom: 16, center: position });

            map.addListener('click', function (event) {
                placeMarker(event.latLng);
            });
        }


        //Llamada ajax al metodo de crear
        $("#submit").click(function (e) {
            e.preventDefault();

            //var token = $('input[name=__RequestVerificationToken]').val();
            if (marker != null) {
                let latitud = marker.position.lat();
                let longitud = marker.position.lng();
                let point = {
                    Nombre: $("#Nombre").val(),
                    Lat: latitud,
                    Long: longitud,
                    Descripcion: $("#Descripcion").val(),
                    TipoPuntoMapaId: $('#TipoPuntoMapaId').val() * 1
                };
                let url = "@Url.Action("Create", "PuntoMapa")";
                $.post(url, point).done(
                    () => (mensaje) {
                        alert(mensaje);
                    }
                ).fail(
                    ()=> {alert("Ajax call failed"); }
                );
            }
            else {
                alert("Debe indicar un punto en el mapa");
            }

        })


        //Crea el punto donde se produce el click en el mapa
        function placeMarker(location) {
            marker = new google.maps.Marker({
                position: location,
                map: map
            });
        }

        $('#remover').click(
            () => {
                marker.map = null;
                marker = null;
            }
        )


    </script>


    <script async defer
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDT4I8iAS4V_drotpXRjk1RjRZsAuKhxqU&callback=initScript">
    </script>
}

InfoColeAplicacion/Views/PuntoMapa/Index.cshtml
<style>
    #map {
        height: 400px;
        width: 100%;
    }
</style>

<div class="row">
    <div class="col-md-8">
        <div id="map"></div>
    </div>
    <div class="col-md-4">
        <div class="form-group">
            <label for="nombre">Nombre</label>
            <input type="text" class="form-control elements" id="nombre" placeholder="">
        </div>

        <div class="form-group">
            <label for="descripcion">Descripcion</label>
            <input type="text" class="form-control elements" id="descripcion" placeholder="">
        </div>

        <label>Tipo de punto</label>
        @Html.DropDownList("Tipos", (List<SelectListItem>)ViewBag.Tipos, htmlAttributes: new { @id = "tipo", @class = "form-control elements" })

        @Html.ActionLink("Agregar punto", "Create", null, new { @class = "btn btn-success btn-lg btn-block elements" })
        <button id="editar" disabled class="btn btn-primary btn-lg btn-block elements">Editar punto</button>
        <button id="borrar" disabled class="btn btn-danger btn-lg btn-block elements">Borrar punto</button>
        <button id="cancelar" disabled class="btn btn-danger btn-lg btn-block elements">Cancelar</button>
    </div>
</div>


@Scripts.Render("~/bundles/jquery")
<script>
    var map;
    var marker = [];
    var selectedMarker = {};

    function initMap() {
        var startPos;

        var geoSuccess  = function (position) {
            startPos = position;
            map = new google.maps.Map(
                document.getElementById('map'), { zoom: 16, center: { lat: startPos.coords.latitude, lng: startPos.coords.longitude } });
            CargarMapa();

        }

        navigator.geolocation.getCurrentPosition(geoSuccess);


        function CargarMapa() {
            let url = "@Url.Action("GetLocations", "PuntoMapa")";
            $.get(url).done(
                function (data) {
                    //console.log(data);
                    for (var i = 0; i < data.length; i++) {
                        let latitud = parseFloat(data[i].Lat);
                        let longitud = parseFloat(data[i].Long);
                        var punto = new google.maps.Marker({
                            position: { lat: latitud, lng: longitud },
                            title: data[i].Nombre,
                            map: map
                        });
                        var puntoId = data[i].PuntoMapaId;
                        var tipo = data[i].TipoPuntoMapaId;
                        var nombre = data[i].Nombre;
                        var descripcion = data[i].Descripcion;
                        
                        
                        google.maps.event.addListener(punto, 'click', (function (punto, puntoId,nombre,tipo,descripcion) {
                            return function () {
                                punto.setDraggable(true);
                                selectedMarker.Nombre = nombre;
                                selectedMarker.PuntoMapaId = puntoId;
                                selectedMarker.TipoPuntoMapaId = tipo;
                                selectedMarker.Marker = punto;

                                $('#nombre').val(selectedMarker.Nombre);
                                $('#tipo').val(selectedMarker.TipoPuntoMapaId);
                                $('#descripcion').val(descripcion);
                                $('#editar').removeAttr("disabled");
                                $('#borrar').removeAttr("disabled");
                                $('#cancelar').removeAttr("disabled");
                            }

                        })(punto, puntoId, nombre, tipo, descripcion));
                    }

                }
            ).fail(
                function () {
                    alert("Ajax call failed");
                }
            );
        }

        $('#editar').click(function (e) {

            let url = "@Url.Action("EditarPunto", "PuntoMapa")";
            let punto = {};
            punto.PuntoMapaId = selectedMarker.PuntoMapaId;
            punto.Nombre = $('#nombre').val();
            punto.Long = selectedMarker.Marker.position.lng();
            punto.Lat = selectedMarker.Marker.position.lat();         
            punto.TipoPuntoMapaId = $('#tipo').val() * 1;
            punto.Descripcion = $('#descripcion').val();
            $.post(url, punto).done(
                function (mensaje) {
                    selectedMarker.Marker.setDraggable(false);
                    selectedMarker = {};
                    LimpiarCampos();
                    $('#editar').attr('disabled', 'disabled');
                    $('#borrar').attr('disabled', 'disabled');
                    $('#cancelar').attr('disabled', 'disabled');
                    alert(mensaje);
                    LimpiarMapa();
                    CargarMapa();
                }
            ).fail(
                function () {
                    alert("Ajax call failed");
                }
            );
        })

        $('#borrar').click(function (e) {
            let url = "@Url.Action("Delete", "PuntoMapa")";

            let id = {};
            id.id = 0;
            id.id = selectedMarker.PuntoMapaId;
            $.post(url, id).done(
                function (mensaje) {
                    selectedMarker.Marker.setMap(null);
                    selectedMarker = {};
                    $('#borrar').attr('disabled', 'disabled');
                    $('#editar').attr('disabled', 'disabled');
                    $('#cancelar').attr('disabled', 'disabled');
                    alert(mensaje);
                }
            ).fail(
                function () {
                    alert("Ajax call failed");
                }
            );
        })

        $('#cancelar').click(function (e) {
            selectedMarker.Marker.setDraggable(false);
            selectedMarker = {};
            $('#editar').attr('disabled', 'disabled');
            $('#borrar').attr('disabled', 'disabled');
            $('#cancelar').attr('disabled', 'disabled');
            LimpiarCampos();
        })
    }
    function LimpiarCampos() {
        $('#nombre').val('');
        $('#descripcion').val('');

    }

    function LimpiarMapa() {
        for (let i = 0; i < marker.length; i++) {
            marker[i].map = null;
            marker[i] = null;

        }
        marker = [];
    }
</script>

<script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDT4I8iAS4V_drotpXRjk1RjRZsAuKhxqU&callback=initMap">

</script>

InfoColeAplicacion/Views/PuntoMapa/IndexUser.cshtml
<style>
    #map {
        height: 400px;
        width: 100%;
    }
</style>

<h4 style="font-family: Verdana">Ubicación de puntos importantes</h4>
<br />
<div>
    <label style="font-family: Verdana">Tipo de punto: </label>
    @Html.DropDownList("TipoPuntoMapaId", (List<SelectListItem>)ViewBag.Tipos, new { htmlAttributes = new { @class = "form-control" } })

    <button id="filtrarPorTipo" class="btn btn-primary elements">Buscar</button>
    <br />
    <br />
    <div id="map"></div>
</div>

@Scripts.Render("~/bundles/jquery")

<script>
    var startPosition = {};
    var markers = [];
    var infoWindows = [];
    function initScript() {
        navigator.geolocation.getCurrentPosition((position) => {

            this.startPosition.Lat = position.coords.latitude;
            this.startPosition.Long = position.coords.longitude;

            var position = { lat: this.startPosition.Lat, lng: this.startPosition.Long };
            initMap(position);
        }, () => {
            this.startPosition.Lat = -27.451102018823633;
            this.startPosition.Long = -58.98655582728293;
            var position = { lat: this.startPosition.Lat, lng: this.startPosition.Long };
            initMap(position);
        });
    }

    function initMap(position) {
            map = new google.maps.Map(
                document.getElementById('map'), { zoom: 16, center: position });
    }

    $('#filtrarPorTipo').click(function (e) {
            var url = "@Url.Action("GetLocationsByType", "PuntoMapa")";
            var tipo = {};
            tipo.tipo = $('#TipoPuntoMapaId').val() * 1;
            console.log(tipo.tipo);
            $.get(url,tipo).done(
                function (data) {
                    LimpiarMapa();
                    if (data.length == 0) {
                        alert("No se han registrado puntos de : " + tipo.tipo);
                    }
                    else {
                            for (let j = 0; j < data.length; j++) {

                                let latitud = parseFloat(data[j].Lat);
                                let longitud = parseFloat(data[j].Long);
                                    var marker = new google.maps.Marker({
                                        position: { lat: latitud, lng: longitud },
                                        map: map,
                                        icon: "/Images/Mapas/LocationPoint.png",
                                        title: 'Punto de: ' + data[j].Tipo.Nombre,
                                });
                                markers.push(marker);
                                if (data[j].Tipo.Nombre == "Parada de Taxi") {
                                    var contentString = '<div class="card" style="width: 18rem; background-color: #FF8000">' +
                                        '<div class="card-body">' +
                                        '<img src = "/Images/Mapas/Car.png" height = "70" class="float-md-right" />' +
                                        '<h5 class="card-title" style="color:white">' + data[j].Tipo.Nombre + '</h5>' +
                                        '<h6 class="card-subtitle mb-2" style="color: lightgrey">' + data[j].Nombre + '</h6>' +
                                        ' <p class="card-text" style="color: white">' + data[j].Descripcion + '</p >' +
                                        '</div>' +
                                        '</div>';
                                } else {
                                    var contentString = '<div class="card" style="width: 18rem; background-color: dodgerblue">' +
                                        '<div class="card-body">' +
                                        '<img src = "/Images/Mapas/SUBE.png" height = "70" class="float-md-right" />' +
                                        '<h5 class="card-title" style="color:white">' + data[j].Tipo.Nombre + '</h5>' +
                                        '<h6 class="card-subtitle mb-2" style="color: lightgrey">' + data[j].Nombre + '</h6>' +
                                        ' <p class="card-text" style="color: white">' + data[j].Descripcion + '</p >' +
                                        '</div>' +
                                        '</div>';
                                    }
                                var infoWindow = new google.maps.InfoWindow({
                                    content: contentString
                                });
                                google.maps.event.addListener(marker, 'mouseover', (function (marker, infoWindow) {
                                    return function () {
                                        infoWindow.open(map, marker);
                                    }
                                })(marker, infoWindow));

                                google.maps.event.addListener(marker, 'mouseout', (function (marker, infoWindow) {
                                    return function () {
                                        infoWindow.close();
                                    }
                                })(marker, infoWindow))
                            }
                        }
                    }
            ).fail(() => alert("Ajax call failed"))
    })

    function LimpiarMapa(){
        for (let i = 0; i < markers.length; i++) {
            markers[i].setMap(null);
        }
        markers = [];
    }


</script>

<script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDT4I8iAS4V_drotpXRjk1RjRZsAuKhxqU&callback=initScript">

</script>